<link rel="stylesheet" type="text/css" href="css/librewifi2.css">

<link rel="stylesheet" type="text/css" href="lib/jquery-easyui-1.4.3/themes/default/easyui.css">
<link rel="stylesheet" type="text/css" href="lib/jquery-easyui-1.4.3/themes/icon.css">
<link rel="stylesheet" type="text/css" href="lib/jquery-easyui-1.4.3/themes/color.css">

<script type="text/javascript" src="lib/jquery-easyui-1.4.3/jquery.min.js"></script>
<script type="text/javascript" src="lib/jquery-easyui-1.4.3/jquery.easyui.min.js"></script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=0.99">
<meta name="description" content="Librewifi2">
